# Generated by Django 5.2.2 on 2025-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrequest',
            name='start_hours_usual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
