# Generated by Django 5.2.2 on 2025-06-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_carrequest_start_hours_usual'),
    ]

    operations = [
    ]
