# Generated by Django 5.2.2 on 2025-06-17 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_carrequest_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='carrequest',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='carrequest',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='carrequest',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='carrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='carrequest',
            name='commentaire',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='carrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du trajet'),
        ),
        migrations.AddField(
            model_name='carrequest',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure de départ'),
        ),
        migrations.AddField(
            model_name='carrequest',
            name='place',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de places'),
        ),
    ]
