# Generated by Django 5.2.2 on 2025-06-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_add_date_time_field'),
        ('request', '0003_auto_20250618_2200'),
    ]

    operations = [
    ]
