# Generated by Django 5.2.3 on 2025-06-17 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0003_remove_carrequest_address_remove_carrequest_arrive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Demande de covoiturage",
                "verbose_name_plural": "Demandes de covoiturage",
            },
        ),
        migrations.AddField(
            model_name="carrequest",
            name="arrive",
            field=models.CharField(
                default="", max_length=255, verbose_name="Point d'arrivée souhaité"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="depart",
            field=models.CharField(
                default="", max_length=255, verbose_name="Point de départ souhaité"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="latitude_arrivee",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Latitude arrivée"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="latitude_depart",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Latitude départ"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="longitude_arrivee",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Longitude arrivée"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="longitude_depart",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Longitude départ"
            ),
        ),
        migrations.AddField(
            model_name="carrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
