# Generated by Django 5.2.3 on 2025-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0004_alter_carrequest_options_carrequest_arrive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrequest",
            name="arrive",
            field=models.CharField(
                max_length=255, verbose_name="Point d'arrivée souhaité"
            ),
        ),
        migrations.AlterField(
            model_name="carrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="carrequest",
            name="depart",
            field=models.CharField(
                max_length=255, verbose_name="Point de départ souhaité"
            ),
        ),
    ]
