# Generated by Django 5.2.2 on 2025-06-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroffer',
            name='address',
            field=models.CharField(default='unknown', max_length=400),
            preserve_default=False,
        ),
    ]
