# Generated by Django 5.2.2 on 2025-06-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_caroffer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caroffer',
            name='address',
        ),
        migrations.AddField(
            model_name='caroffer',
            name='start_point_usual',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
