# Generated by Django 5.2.2 on 2025-06-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_caroffer_address_caroffer_start_point_usual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caroffer',
            options={'ordering': ['-date_time']},
        ),
    ]
