# Generated by Django 5.2.2 on 2025-06-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_caroffer_options'),
        ('offer', '0005_add_day_field'),
    ]

    operations = [
    ]
