# Generated by Django 5.2.2 on 2025-06-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_merge_0004_alter_caroffer_options_0005_add_day_field'),
    ]

    operations = [
    ]
