# Generated by Django 5.2.2 on 2025-06-18 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_add_hour_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroffer',
            name='day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caroffer',
            name='hour',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caroffer',
            name='matricule',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
