# Generated by Django 5.2.3 on 2025-06-17 22:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("conducteur", "Conducteur"),
                            ("passager", "Passager"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region="BJ", unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "point_depart_habituel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Point de départ habituel",
                    ),
                ),
                (
                    "latitude_depart_habituel",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude départ habituel"
                    ),
                ),
                (
                    "longitude_depart_habituel",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude départ habituel"
                    ),
                ),
                (
                    "horaires_depart_habituel",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Horaires de départ habituels",
                    ),
                ),
                (
                    "horaires_arrivee_habituel",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Horaires d'arrivée habituels",
                    ),
                ),
                (
                    "marque_vehicule",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Marque du véhicule",
                    ),
                ),
                (
                    "modele_vehicule",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Modèle du véhicule",
                    ),
                ),
                (
                    "couleur_vehicule",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Couleur du véhicule",
                    ),
                ),
                (
                    "nombre_places_vehicule",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Nombre de places véhicule",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="user_groups",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
        ),
    ]
