# Generated by Django 5.2.2 on 2025-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
